### ISSUE TITLE
Use temporary key to sign messages

### ISSUE THREAD

**Issue by yihuang** [mpc-poker/prototype#12]
Using a temporary key to sign the messages can improve the UX a lot, because the client can sign the messages automatically without go to metamask all the time.
The temporary key is created when join the game, and destroyed after the game is finished.

TODO: Security Implications?

**Comment by yijiasu-crypto** [comment]
There is no additional security exposure if:

1.  The "temporary private key" is, and will not be used on a mainnet: 1) We will generate this private key only during the creation of local EVM, using a random seed provided by system. 2) We will not allow the user to export this temp key or reveal its credentials. 3) Every time we start a new game, this temporary key will be reused.
2. The location of this temporary key being store: 1) In RAM inside JS context -- which is protected by the browser itself from outer access. should be secure  2) Inside `localStorage` if we persist this across sessions (if we don't persist the key, users can still play the game without closing the browser window)
3. We will not send any asset to this key as well.

**Comment by yijiasu-crypto** [comment]
There is no additional security exposure if:

1.  The "temporary private key" is, and will not be used on a mainnet: 1) We will generate this private key only during the creation of local EVM, using a random seed provided by system. 2) We will not allow the user to export this temp key or reveal its credentials. 3) Every time we start a new game, this temporary key will be reused.
2. The location of this temporary key being store: 1) In RAM inside JS context -- which is protected by the browser itself from outer access. should be secure  2) Inside `localStorage` if we persist this across sessions (if we don't persist the key, users can still play the game without closing the browser window)
3. We will not send any asset to this key as well.

**Comment by yijiasu-crypto** [comment]
However we should think about if the user need to start the `recovery` function on-chain, will he need to use this key for any interaction?

**Comment by yijiasu-crypto** [comment]
However we should think about if the user need to start the `recovery` function on-chain, will he need to use this key for any interaction?

**Comment by yihuang** [comment]
> However we should think about if the user need to start the `recovery` function on-chain, will he need to use this key for any interaction?

he still need this account to sign the messages, but use any account to pay the gas for calling the `processMessage` method.

**Comment by yihuang** [comment]
done
